# Generated by Django 3.2 on 2021-06-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
