# Generated by Django 3.2 on 2021-06-08 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_brandproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecom.brand'),
        ),
        migrations.DeleteModel(
            name='BrandProduct',
        ),
    ]
