# Generated by Django 3.2 on 2021-06-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0018_auto_20210611_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_of_items',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
