# Generated by Django 3.2 on 2021-06-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0019_auto_20210612_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(null=True),
        ),
    ]
