# Generated by Django 3.2 on 2021-06-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0020_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='size',
            field=models.FloatField(default=8, null=True),
        ),
    ]
