# Generated by Django 3.2 on 2021-06-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0021_orderproduct_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='size',
            field=models.IntegerField(default=8, null=True),
        ),
    ]
